# Generated by Django 2.0 on 2018-02-02 17:57

import blogap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blogap.models.get_image_path),
        ),
    ]
