# Generated by Django 2.0 on 2017-12-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_link', models.CharField(max_length=200)),
                ('choice', models.IntegerField(default=1)),
                ('dw_date', models.DateTimeField(verbose_name='downloaded on')),
            ],
        ),
    ]
