# Generated by Django 2.0 on 2018-04-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
    ]
